export const minutes = [
    { value: "00", label: "00" },
    { value: "01", label: "01" },
    { value: "02", label: "02" },
    { value: "03", label: "03" },
    { value: "04", label: "04" },
    { value: "05", label: "05" },
    { value: "06", label: "06" },
    { value: "07", label: "07" },
    { value: "08", label: "08" },
    { value: "09", label: "09" },
    { value: "10", label: "10" },
    { value: "11", label: "11" },
    { value: "12", label: "12" },
    { value: "13", label: "13" },
    { value: "14", label: "14" },
    { value: "15", label: "15" },
    { value: "16", label: "16" },
    { value: "17", label: "17" },
    { value: "18", label: "18" },
    { value: "19", label: "19" },
    { value: "20", label: "20" },
    { value: "21", label: "21" },
    { value: "22", label: "22" },
    { value: "23", label: "23" },
    { value: "24", label: "24" },
    { value: "25", label: "25" },
    { value: "26", label: "26" },
    { value: "27", label: "27" },
    { value: "28", label: "28" },
    { value: "29", label: "29" },
    { value: "30", label: "30" },
    { value: "31", label: "31" },
    { value: "32", label: "32" },
    { value: "33", label: "33" },
    { value: "34", label: "34" },
    { value: "35", label: "35" },
    { value: "36", label: "36" },
    { value: "37", label: "37" },
    { value: "38", label: "38" },
    { value: "39", label: "39" },
    { value: "40", label: "40" },
    { value: "41", label: "41" },
    { value: "42", label: "42" },
    { value: "43", label: "43" },
    { value: "44", label: "44" },
    { value: "45", label: "45" },
    { value: "46", label: "46" },
    { value: "47", label: "47" },
    { value: "48", label: "48" },
    { value: "49", label: "49" },
    { value: "50", label: "50" },
    { value: "51", label: "51" },
    { value: "52", label: "52" },
    { value: "53", label: "53" },
    { value: "54", label: "54" },
    { value: "55", label: "55" },
    { value: "56", label: "56" },
    { value: "57", label: "57" },
    { value: "58", label: "58" },
    { value: "59", label: "59" },
];
export const hours = [
    { value: "00", label: "00" },
    { value: "01", label: "01" },
    { value: "02", label: "02" },
    { value: "03", label: "03" },
    { value: "04", label: "04" },
    { value: "05", label: "05" },
    { value: "06", label: "06" },
    { value: "07", label: "07" },
    { value: "08", label: "08" },
    { value: "09", label: "09" },
    { value: "10", label: "10" },
    { value: "11", label: "11" },
    { value: "12", label: "12" },
    { value: "13", label: "13" },
    { value: "14", label: "14" },
    { value: "15", label: "15" },
    { value: "16", label: "16" },
    { value: "17", label: "17" },
    { value: "18", label: "18" },
    { value: "19", label: "19" },
    { value: "20", label: "20" },
    { value: "21", label: "21" },
    { value: "22", label: "22" },
    { value: "23", label: "23" },
];
export const days = [
    { value: "Sunday", label: "Sunday" },
    { value: "Monday", label: "Monday" },
    { value: "Tuesday", label: "Tuesday" },
    { value: "Wednesday", label: "Wednesday" },
    { value: "Thursday", label: "Thursday" },
    { value: "Friday", label: "Friday" },
    { value: "Saturday", label: "Saturday" },
];
export const TAMM_Authorization = [
    { value: "active", label: "Active" },
    { value: "inactive", label: "Inactive" },
];
export const nodhom = [
    { value: "enable", label: "Enable" },
    { value: "disable", label: "Disable" },
];
export const countries = [
    { value: 183, label: "Saudi Arabia" },
    { value: 184, label: "Bahrain" },
    { value: 185, label: "UAE" },
];
export const tajeerLicense = [
    { value: "11001100110011", label: "11001100110011" },
    { value: "11002300110011", label: "11002300110011" },
];
export const cities = [
    { value: 7, label: "Riyadh" },
    { value: 31, label: "Dammam" },
    { value: 32, label: "Tabuk" },
    { value: 33, label: "Jeddah" },
    { value: 34, label: "Madinah" },
    { value: 35, label: "makkah" },
];
export const access = [
    { value: "0", label: "No Access" },
    { value: "1", label: "View Only" },
    { value: "2", label: "Create" },
    { value: "3", label: "Edit" },
    { value: "4", label: "Full Access" },
];
export const accessModule = [
    { value: "0", label: "No Access" },
    { value: "1", label: "Access" },
];
export const Contracts = [
    {
        contract_number: "100061",
        car_type: "SUV",
        make: { id: 1, name_en: "Lexus", name_ar: "Lexus" },
        model: { id: 1, name_en: "ES", name_ar: "ES" },
        year: "2023",
        customer_name: "Shazam", advance_amount: "10", checkout_time: "11:18", color: "blue",
        rental_cost: "3452",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100062",
        car_type: "Sedan",
        make: { id: 1, name_en: "Lexus", name_ar: "Lexus" },
        model: { id: 1, name_en: "ES", name_ar: "ES" },
        year: "2023",
        customer_name: "Shazam", advance_amount: "10", rental_cost: "3452", checkout_time: "11:18", color: "red",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100063",
        car_type: "Bus",
        make: { id: 1, name_en: "Lexus", name_ar: "Lexus" },
        model: { id: 1, name_en: "ES", name_ar: "ES" },
        year: "2023",
        customer_name: "Shazam",
        issue_date: "2023-01-01", advance_amount: "10", rental_cost: "3452", checkout_time: "11:18", color: "green",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100064",
        car_type: "Pickup",
        make: { id: 1, name_en: "Lexus", name_ar: "Lexus" },
        model: { id: 1, name_en: "ES", name_ar: "ES" },
        year: "2023",
        customer_name: "Shazam", advance_amount: "10", rental_cost: "3452", checkout_time: "11:18", color: "yellow",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100063",
        car_type: "Bus",
        make: { id: 1, name_en: "Lexus", name_ar: "Lexus" },
        model: { id: 1, name_en: "ES", name_ar: "ES" },
        year: "2023",
        customer_name: "Shazam",
        issue_date: "2023-01-01", advance_amount: "10", rental_cost: "3452", checkout_time: "11:18", color: "green",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100066",
        car_type: "Luxury",
        make: { id: 1, name_en: "Lexus", name_ar: "Lexus" },
        model: { id: 1, name_en: "ES", name_ar: "ES" },
        year: "2023",
        customer_name: "Shazam", advance_amount: "10", rental_cost: "3452", checkout_time: "11:18", color: "black",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100067",
        car_type: "Family",
        make: { id: 1, name_en: "Lexus", name_ar: "Lexus" },
        model: { id: 1, name_en: "ES", name_ar: "ES" },
        year: "2023",
        customer_name: "Shazam", advance_amount: "10", rental_cost: "3452", checkout_time: "11:18", color: "blue",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100068",
        car_type: "Sedan",
        make: { id: 1, name_en: "Lexus", name_ar: "Lexus" },
        model: { id: 1, name_en: "ES", name_ar: "ES" },
        year: "2023",
        customer_name: "Shazam", advance_amount: "10", rental_cost: "3452", checkout_time: "11:18", color: "gray",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100069",
        car_type: "SUV",
        make: { id: 1, name_en: "Lexus", name_ar: "Lexus" },
        model: { id: 1, name_en: "ES", name_ar: "ES" },
        year: "2023",
        customer_name: "Shazam", advance_amount: "10", rental_cost: "3452", checkout_time: "11:18", color: "red",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100070",
        car_type: "Luxury",
        make: { id: 1, name_en: "Lexus", name_ar: "Lexus" },
        model: { id: 1, name_en: "ES", name_ar: "ES" },
        year: "2023",
        customer_name: "Shazam", advance_amount: "10", rental_cost: "3452", checkout_time: "11:18", color: "green",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    }

];
export const header_card_dashboard = [
    {
        color: "#1281C4",
        bcolor: "#1281c44a",
        card_number: "20,425",
        car_title: "Cars Overdue",
        icon: "overdueSvg",
    },
    {
        color: "#ff0000",
        bcolor: "#ff000054",
        card_number: "20,425",
        car_title: "Alerts",
        icon: "alertsSvg",
    },
    {
        color: "#13ae05",
        bcolor: "#24971959",
        card_number: "20,425",
        car_title: "Cash Registered",
        icon: "payments",
    },
    {
        color: "#800080",
        bcolor: "#8000806b",
        card_number: "20,425",
        car_title: "Disputed contract",
        icon: "contracts",
    },
];
export const header_card = [
    {
        color: "#1281C4",
        bcolor: "#1281c44a",
        card_number: "30",
        car_title: "Total cars",
        icon: "carTotalSvg",
    },
    {
        color: "#02B2AF",
        bcolor: "#02b2af45",
        card_number: "10",
        car_title: "Available",
        icon: "availableCars",
    },
    {
        color: "#2E96FF",
        bcolor: "#2e96ff59",
        card_number: "10",
        car_title: "Rented",
        icon: "carRentedSvg",
    },
    {
        color: "#B800D8",
        bcolor: "#b800d859",
        card_number: "25",
        car_title: "Overdue",
        icon: "overdueSvg",
    },
    {
        color: "#60009B",
        bcolor: "#60009b59",
        card_number: "20",
        car_title: "Workshop",
        icon: "carWorkshopSvg",
    },
    {
        color: "#03008D",
        bcolor: "#03008d5c",
        card_number: "0",
        car_title: "Accident",
        icon: "carAccidentSvg",
    },
    {
        color: "#ff0000",
        bcolor: "#ff000054",
        card_number: "2",
        car_title: "Alert",
        icon: "alertsSvg",
    },
    {
        color: "#13ae05",
        bcolor: "#24971959",
        card_number: "20",
        car_title: "Inactive",
        icon: "carInactiveSvg",
    },
    {
        color: "#2731C8",
        bcolor: "#2731c859",
        card_number: "25",
        car_title: "Stolen",
        icon: "carStolenSvg",
    },
    {
        color: "#800080",
        bcolor: "#8000806b",
        card_number: "25",
        car_title: "Branch Access",
        icon: "contracts",
    },
];
export const contract_header_card = [
    {
        color: "#1281C4",
        bcolor: "#1281c44a",
        card_number: "2",
        car_title: "Cars Overdue",
        icon: "clockSvg",
    },
    {
        color: "#ff0000",
        bcolor: "#ff000054",
        card_number: "4",
        car_title: "Rented In branch",
        icon: "cars",
    },
    {
        color: "#13ae05",
        bcolor: "#24971959",
        card_number: "79241",
        car_title: "Estimate today's Income",
        icon: "payments",
    },
    {
        color: "#800080",
        bcolor: "#8000806b",
        card_number: "558",
        car_title: "Returns Tomorrow",
        icon: "secureSvg",
    },
];
export const car_specs = [
    {
        make_model: "Hyundai Elentra",
        year: "2016",
        rent_per_day: "120",
        transmition: "manual",
        mileage: "22432",
        rented_times: "12",
        car_plate: "1253 VDJ",
        color: "red",
        icon: "hyundaiSvg",
        fuel_type: "petrol 91",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "economic",
        dail_km_limit: "200.00",
    },
    {
        make_model: "Toyota Camry",
        year: "2023",
        rent_per_day: "120",
        transmition: "auto",
        mileage: "22432",
        rented_times: "4",
        car_plate: "123 MNA",
        color: "black",
        icon: "toyotaSvg",
        fuel_type: "petrol 95",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "pickup",
        dail_km_limit: "200.00",
    },
    {
        make_model: "XLT (200A) 4X2",
        year: "2023",
        rent_per_day: "120",
        transmition: "auto",
        mileage: "22432",
        rented_times: "12",
        car_plate: "1253 VDJ",
        color: "blue",
        icon: "fordSvg",
        fuel_type: "petrol 91",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "suv",
        dail_km_limit: "200.00",
    },
    {
        make_model: "Toyota Hilux Double Cab",
        year: "2023",
        rent_per_day: "150",
        transmition: "auto",
        mileage: "22432",
        rented_times: "1",
        car_plate: "1245 TUR",
        color: "black",
        icon: "toyotaSvg",
        fuel_type: "petrol 95",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "economic",
        dail_km_limit: "200.00",
    },
    {
        make_model: "Kia Picanto",
        year: "2016",
        rent_per_day: "120",
        transmition: "auto",
        mileage: "22432",
        rented_times: "12",
        car_plate: "4467 KYT",
        color: "blue",
        icon: "kiaSvg",
        fuel_type: "petrol 91",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "pickup",
        dail_km_limit: "200.00",
    },
    {
        make_model: "Hyundai Tucson",
        year: "2022",
        rent_per_day: "140",
        transmition: "auto",
        mileage: "224432",
        rented_times: "3",
        car_plate: "1773 HGF",
        color: "Purple",
        icon: "hyundaiSvg",
        fuel_type: "petrol 95",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "suv",
        dail_km_limit: "200.00",
    },
    {
        make_model: "Honda Accord",
        year: "2015",
        rent_per_day: "100",
        transmition: "auto",
        mileage: "224377",
        rented_times: "15",
        car_plate: "8976 ANP",
        color: "lightgray",
        icon: "hondaSvg",
        fuel_type: "petrol 91",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "economic",
        dail_km_limit: "200.00",
    },

    {
        make_model: "Sportage Plug-in Hybrid",
        year: "2019",
        rent_per_day: "120",
        transmition: "auto",
        mileage: "22432",
        rented_times: "12",
        car_plate: "1253 VDJ",
        color: "purple",
        icon: "kiaSvg",
        fuel_type: "petrol 95",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "suv",
    },
    {
        make_model: "Nissan Sunny",
        year: "2018",
        rent_per_day: "100",
        transmition: "auto",
        mileage: "274422",
        rented_times: "12",
        car_plate: "1783 UNS",
        color: "black",
        icon: "nissanSvg",
        fuel_type: "petrol 95",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "pickup",
    },
    {
        make_model: "Hyundai Elentra",
        year: "2016",
        rent_per_day: "120",
        transmition: "auto",
        mileage: "22432",
        rented_times: "12",
        car_plate: "1253 VDJ",
        color: "brown",
        icon: "hyundaiSvg",
        fuel_type: "petrol 91",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "sedan",
        dail_km_limit: "200.00",
    },
    {
        make_model: "Nissan Patrol Pickup",
        year: "2019",
        rent_per_day: "100",
        transmition: "manual",
        mileage: "34432",
        rented_times: "12",
        car_plate: "5534 NIA",
        color: "white",
        icon: "nisaanSvg",
        fuel_type: "petrol 95",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "pickup",
        dail_km_limit: "200.00",
    },
];
export const line_chart_dataset = [
    {
        country: 'World',
        year: 2013,
        Available: 61,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
    },
    {
        country: 'World',
        year: 2014,
        Available: 700,
        Rented: 40,
        Overdue: 203,
        Workshop: 21,
        Stolen: 15,
        Accident: 15,
        Inactive: 15,
    },
    {
        country: 'World',
        year: 2015,
        Available: 600,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
    },
    {
        country: 'World',
        year: 2016,
        Available: 100,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
    },
    {
        country: 'World',
        year: 2017,
        Available: 300,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
    },
    {
        country: 'World',
        year: 2018,
        Available: 500,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
    },
    {
        country: 'World',
        year: 2019,
        Available: 200,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
    },
    {
        country: 'World',
        year: 2020,
        Available: 300,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
    },
    {
        country: 'World',
        year: 2021,
        Available: 500,
        Rented: 0,
        Overdue: 10,
        Workshop: 50,
        Stolen: 50,
        Accident: 20,
        Inactive: 20,
    },
    {
        country: 'World',
        year: 2022,
        Available: 1,
        Rented: 0,
        Overdue: 3,
        Workshop: 25,
        Stolen: 25,
        Accident: 5,
        Inactive: 5,
    },
    {
        country: 'World',
        year: 2023,
        Available: 6,
        Rented: 7,
        Overdue: 10,
        Workshop: 2,
        Stolen: 5,
        Accident: 2,
        Inactive: 5,
    },
];
export const chart_dataset = [
    {
        Available: 61,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
        month: "Jan",
    },
    {
        Available: 62,
        Rented: 40,
        Overdue: 203,
        Workshop: 21,
        Stolen: 15,
        Accident: 15,
        Inactive: 15,
        month: "Fev",
    },
    {
        Available: 61,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
        month: "Mar",
    },
    {
        Available: 61,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
        month: "Apr",
    },
    {
        Available: 61,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
        month: "May",
    },
    {
        Available: 61,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
        month: "June",
    },
    {
        Available: 61,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
        month: "July",
    },
    {
        Available: 61,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
        month: "Aug",
    },
    {
        Available: 61,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
        month: "Sept",
    },
    {
        Available: 61,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
        month: "Oct",
    },
    {
        Available: 61,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
        month: "Nov",
    },
    {
        Available: 61,
        Rented: 70,
        Overdue: 103,
        Workshop: 25,
        Stolen: 25,
        Accident: 25,
        Inactive: 25,
        month: "Dec",
    },
];
export const Car_chart_data = [
    { id: 0, value: 10, label: "Total Available Cars" },
    { id: 1, value: 10, label: "Rented Cars" },
    { id: 2, value: 10, label: "Cars Overdue" },
    { id: 3, value: 10, label: "Cars in Workshop" },
    { id: 4, value: 10, label: "Cars Stolen" },
    { id: 5, value: 10, label: "Cars Accident" },
    { id: 6, value: 10, label: "Inactive" },
];
export const carplate = {
    plateText1_ar: "ا",
    plateText2_ar: "ا",
    plateText3_ar: "ن",
    plateNo: "4321",
    plateText1_en: "A",
    plateText2_en: "A",
    plateText3_en: "N",
};
export const Contracts_chart_data = [
    { id: 0, value: 10, label: "All" },
    { id: 1, value: 15, label: "Individual" },
    { id: 2, value: 20, label: "Compnay" },
];
export const switch_data = [
    {
        title: "Edit dates",
        info: "Giving the ability to user to change the date",
        name: "isDateEnable",
    },
    {
        title: "Block Customer",
        info: "Giving the user the ability to block customer",
        name: "isBlockEnable",
    },
    {
        title: "Status",
        info: "Determine if the user account active or inactive",
        name: "active",
    },
    {
        title: "Delete Contract",
        info: "Giving the user the ability to delete the closed contract",
        name: "isDeleteContract",
    },
    {
        title: "Discount Receipt",
        info: "Give the user the authority to discount the Pending Receivables.",
        name: "isDiscountReceipt",
    },
    {
        title: "Delete Receipts",
        info: "Give the user the authority to delete the Pending Payables and Receiables. Liquidation bonds are not included in this property",
        name: "isDeleteAvailable",
    },
    {
        title: "Resend To Nozhum",
        info: "For establishments that have activated the link with the systems program, giving the authority to resend all contracts and operations to systems",
        name: "isReSendNozumAvailable",
    },
    {
        title: "Tajeer Rent contract is mandatory",
        info: "You can force the user to issue and return contracts for the rental platform only from the Ministry of Transport, when you activate this feature for the user, he cannot issue regular lease contracts or return them",
        name: "isTajeerAvailable",
    },
    {
        title: "Quick customer creation",
        info: "When this option is disabled, the user will not be able to add a new customer quickly through the Create Lease Contract page, and it requires adding the customer on the Customers page and then opening a new contract for him",
        name: "isQuickAddCustomer",
    },
];
export const language = [
    { label: "English", value: "en" },
    { label: "العربية", value: "ar" },
];
export const bodyObjectCar = {
    plateNo: 0,
    plateText1_en: "",
    plateText2_en: "",
    plateText3_en: "",
    plateText1_ar: "",
    plateText2_ar: "",
    plateText3_ar: "",
    plateTypeID: 0,
    chasisNo: "",
    sequenceNo: "",
    buyingDate: "",
    colorID: 0,
    carTypeID: 0,
    transmissionID: 0,
    makeID: 0,
    modelID: 0,
    year: 0,
    mileage: "",
    dailyRent: 0,
    weeklyRent: 0,
    monthlyRent: 0,
    minDailyRent: 0,
    perExtraKM: 0,
    dailyKMlimit: 0,
    graceHours: 0,
    graceCharge: 0,
    insuranceID: 0,
    insuranceTypeID: 0,
    policyNo: "",
    insurancePenality: "",
    insuranceExpDate: "",
    registrationExpHijiri: "",
    inspectionExpHijiri: "",
    branchID: 0,
    fuelTypeID: 0,
    puchaseCost: 0,
    fullFuelCost: "",
    operatingCardNo: "",
    operatingCardIssueDate: "",
    operatingCardExpDate: "",
    active: "",
};
export const bodyObjecCustomer = {

    category: 0,
    idType: 0,
    idNumber: "",
    version: 0,
    idissuecity: 0,
    idExpiryDate_hijri: "",
    idExpiryDate_gregorian: "",
    licenseNo: "",
    licExpiryDate_hijri: "",
    licenseExpDate_gregorian: "",
    fullname_en: "",
    fullname_ar: "",
    mobileNo: 0,
    email: "",
    dob_hijri: "",
    dob_gregorian: "",
    idIssueCountry: 0,
    employerName: "",
    pricelist: 0,
    nationality: 0,
    residentCity: 0,
    homePhone: "",
    workPhone: "",
    comments: "",
    active: "",
    cA_buildingNo: 0,
    cA_StreetName: 0,
    cA_District: 0,
    cA_City: 0,
    cA_Country: 0,
    cA_PostalCode: 0,
    cA_AdditionalPostalCode: 0,
    vatNumber: "0"
}
export const category = [
    { label: "Individual", value: "individual" },
    { label: "Company", value: "company" },
];
export const IdentityCategory = [
    { label: "Resident", value: "resident" },
    { label: "NON-Resident", value: "non-resident" },
];
export const IDType = [
    { label: "Citizen ID", value: "Citizen ID" },
    { label: "Resident ID", value: "Resident ID" },
    { label: "Visitor", value: "Visitor" },
    { label: "Citizens of GCC", value: "Citizens of GCC" },
];
export const contractType = [
    { label: "With Driver", value: "With Driver" },
    { label: "Without Driver", value: "Without Driver" },
];
export const returnBranch = [
    { label: "Head", value: "Head" },
    { label: "dammam", value: "dammam" },
];
export const payment = [
    { label: "ATM", value: "ATM" },
    { label: "Cash", value: "Cash" },
    { label: "Credit", value: "Credit" },
    { label: "Sadad", value: "Sadad" },
    { label: "Cheque", value: "Cheque" },
    { label: "Bank Transfer", value: "Bank Transfer" },
];
export const paymentStatus = [
    { label: "Continuous", value: "continuous" },
    { label: "Freeze", value: "freeze" },

];
export const PaymentTable = [
    {
        receipt_no: "AR10167",
        activity: "voilation",
        payment_type: "Cash",
        payment_date: "28/07/2023",
        branch: "head",
        amount: "50",
    },
    {
        receipt_no: "AR10167",
        activity: "voilation",
        payment_type: "Cash",
        payment_date: "28/07/2023",
        branch: "head",
        amount: "50",
    }, {
        receipt_no: "AR10167",
        activity: "voilation",
        payment_type: "Cash",
        payment_date: "28/07/2023",
        branch: "head",
        amount: "50",
    }, {
        receipt_no: "AR10167",
        activity: "voilation",
        payment_type: "Cash",
        payment_date: "28/07/2023",
        branch: "head",
        amount: "50",
    }, {
        receipt_no: "AR10167",
        activity: "voilation",
        payment_type: "Cash",
        payment_date: "28/07/2023",
        branch: "head",
        amount: "50",
    }, {
        receipt_no: "AR10167",
        activity: "voilation",
        payment_type: "Cash",
        payment_date: "28/07/2023",
        branch: "head",
        amount: "50",
    }, {
        receipt_no: "AR10167",
        activity: "voilation",
        payment_type: "Cash",
        payment_date: "28/07/2023",
        branch: "head",
        amount: "50",
    }, {
        receipt_no: "AR10167",
        activity: "voilation",
        payment_type: "Cash",
        payment_date: "28/07/2023",
        branch: "head",
        amount: "50",
    }, {
        receipt_no: "AR10167",
        activity: "voilation",
        payment_type: "Cash",
        payment_date: "28/07/2023",
        branch: "head",
        amount: "50",
    }, {
        receipt_no: "AR10167",
        activity: "voilation",
        payment_type: "Cash",
        payment_date: "28/07/2023",
        branch: "head",
        amount: "50",
    }, {
        receipt_no: "AR10167",
        activity: "voilation",
        payment_type: "Cash",
        payment_date: "28/07/2023",
        branch: "head",
        amount: "50",
    }, {
        receipt_no: "AR10167",
        activity: "voilation",
        payment_type: "Cash",
        payment_date: "28/07/2023",
        branch: "head",
        amount: "50",
    },
];
export const modde = [
    { label: "Advance", value: "Advance" },
    { label: "Reservation", value: "Reservation" },
];
export const status = [
    { label: "Stolen", value: "Stolen" },
    { label: "Return", value: "Return" },
    { label: "Accident", value: "Accident" },
];
export const evalueation = [
    { label: "★★★★★", value: 5 },
    { label: "★★★★", value: 4 },
    { label: "★★★", value: 3 },
    { label: "★★", value: 2 },
    { label: "★", value: 1 },
];
export const bank = [
    { label: "Al Rajhi", value: "Al Rajhi" },
    { label: "Al Bilad", value: "Al Bilad" },
    { label: "Riyadh Bank", value: "Riyadh Bank" },
    { label: "SNB", value: "SNB" },
];
