export const minutes = [
    { value: "00", label: "00" },
    { value: "01", label: "01" },
    { value: "02", label: "02" },
    { value: "03", label: "03" },
    { value: "04", label: "04" },
    { value: "05", label: "05" },
    { value: "06", label: "06" },
    { value: "07", label: "07" },
    { value: "08", label: "08" },
    { value: "09", label: "09" },
    { value: "10", label: "10" },
    { value: "11", label: "11" },
    { value: "12", label: "12" },
    { value: "13", label: "13" },
    { value: "14", label: "14" },
    { value: "15", label: "15" },
    { value: "16", label: "16" },
    { value: "17", label: "17" },
    { value: "18", label: "18" },
    { value: "19", label: "19" },
    { value: "20", label: "20" },
    { value: "21", label: "21" },
    { value: "22", label: "22" },
    { value: "23", label: "23" },
    { value: "24", label: "24" },
    { value: "25", label: "25" },
    { value: "26", label: "26" },
    { value: "27", label: "27" },
    { value: "28", label: "28" },
    { value: "29", label: "29" },
    { value: "30", label: "30" },
    { value: "31", label: "31" },
    { value: "32", label: "32" },
    { value: "33", label: "33" },
    { value: "34", label: "34" },
    { value: "35", label: "35" },
    { value: "36", label: "36" },
    { value: "37", label: "37" },
    { value: "38", label: "38" },
    { value: "39", label: "39" },
    { value: "40", label: "40" },
    { value: "41", label: "41" },
    { value: "42", label: "42" },
    { value: "43", label: "43" },
    { value: "44", label: "44" },
    { value: "45", label: "45" },
    { value: "46", label: "46" },
    { value: "47", label: "47" },
    { value: "48", label: "48" },
    { value: "49", label: "49" },
    { value: "50", label: "50" },
    { value: "51", label: "51" },
    { value: "52", label: "52" },
    { value: "53", label: "53" },
    { value: "54", label: "54" },
    { value: "55", label: "55" },
    { value: "56", label: "56" },
    { value: "57", label: "57" },
    { value: "58", label: "58" },
    { value: "59", label: "59" },
];
export const hours = [
    { value: "00", label: "00" },
    { value: "01", label: "01" },
    { value: "02", label: "02" },
    { value: "03", label: "03" },
    { value: "04", label: "04" },
    { value: "05", label: "05" },
    { value: "06", label: "06" },
    { value: "07", label: "07" },
    { value: "08", label: "08" },
    { value: "09", label: "09" },
    { value: "10", label: "10" },
    { value: "11", label: "11" },
    { value: "12", label: "12" },
    { value: "13", label: "13" },
    { value: "14", label: "14" },
    { value: "15", label: "15" },
    { value: "16", label: "16" },
    { value: "17", label: "17" },
    { value: "18", label: "18" },
    { value: "19", label: "19" },
    { value: "20", label: "20" },
    { value: "21", label: "21" },
    { value: "22", label: "22" },
    { value: "23", label: "23" },
];
export const days = [
    { value: "Sunday", label: "Sunday" },
    { value: "Monday", label: "Monday" },
    { value: "Tuesday", label: "Tuesday" },
    { value: "Wednesday", label: "Wednesday" },
    { value: "Thursday", label: "Thursday" },
    { value: "Friday", label: "Friday" },
    { value: "Saturday", label: "Saturday" },
];
export const TAMM_Authorization = [
    { value: "active", label: "Active" },
    { value: "inactive", label: "Inactive" },
];
export const nodhom = [
    { value: "enable", label: "Enable" },
    { value: "disable", label: "Disable" },
];
export const countries = [
    { value: 183, label: "Saudi Arabia" },
    { value: 184, label: "Bahrain" },
    { value: 185, label: "UAE" },
];
export const tajeerLicense = [
    { value: "11001100110011", label: "11001100110011" },
    { value: "11002300110011", label: "11002300110011" },
];
export const cities = [
    { value: 7, label: "Riyadh" },
    { value: 31, label: "Dammam" },
    { value: 32, label: "Tabuk" },
    { value: 33, label: "Jeddah" },
    { value: 34, label: "Madinah" },
    { value: 35, label: "makkah" },
];
export const access = [
    { value: "0", label: "No Access" },
    { value: "1", label: "View Only" },
    { value: "2", label: "Create" },
    { value: "3", label: "Edit" },
    { value: "4", label: "Full Access" },
];
export const accessModule = [
    { value: "0", label: "No Access" },
    { value: "1", label: "Access" },
];
export const Contracts = [
    {
        contract_number: "100061",
        car_plate: "a a y 1135 ا ا ن",
        make_model: "Lexus/ES",
        customer_name: "Shazam",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100062",
        car_plate: "a a y 1135 ا ا ن",
        make_model: "Lexus/ES",
        customer_name: "Shazam",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100063",
        car_plate: "a a y 1135 ا ا ن",
        make_model: "Lexus/ES",
        customer_name: "Shazam",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100064",
        car_plate: "a a y 1135 ا ا ن",
        make_model: "Lexus/ES",
        customer_name: "Shazam",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100065",
        car_plate: "a a y 1135 ا ا ن",
        make_model: "Lexus/ES",
        customer_name: "Shazam",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100066",
        car_plate: "a a y 1135 ا ا ن",
        make_model: "Lexus/ES",
        customer_name: "Shazam",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100067",
        car_plate: "a a y 1135 ا ا ن",
        make_model: "Lexus/ES",
        customer_name: "Shazam",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100068",
        car_plate: "a a y 1135 ا ا ن",
        make_model: "Lexus/ES",
        customer_name: "Shazam",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100069",
        car_plate: "a a y 1135 ا ا ن",
        make_model: "Lexus/ES",
        customer_name: "Shazam",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "100070",
        car_plate: "a a y 1135 ا ا ن",
        make_model: "Lexus/ES",
        customer_name: "Shazam",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "CO100000",
        company_number: "112211211111",
        company_name: "Ok Group",
        assigned_cars: "25",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
    {
        contract_number: "CO100001",
        company_number: "8967451254",
        company_name: "ABC Group",
        assigned_cars: "14",
        issue_date: "2023-01-01",
        return_date: "2023-01-20",
    },
];
export const header_card = [
    {
        color: "#1281C4",
        bcolor: "#1281c44a",
        card_number: "20,425",
        car_title: "Cars Overdue",
        icon: "overdueSvg",
    },
    {
        color: "#ff0000",
        bcolor: "#ff000054",
        card_number: "20,425",
        car_title: "Alerts",
        icon: "alertsSvg",
    },
    {
        color: "#13ae05",
        bcolor: "#24971959",
        card_number: "20,425",
        car_title: "Cash Registered",
        icon: "payments",
    },
    {
        color: "#800080",
        bcolor: "#8000806b",
        card_number: "20,425",
        car_title: "Disputed contract",
        icon: "contracts",
    },
];
export const car_specs = [
    {
        make_model: "Hyundai Elentra",
        year: "2016",
        rent_per_day: "120",
        transmition: "manual",
        mileage: "22432",
        rented_times: "12",
        car_plate: "1253 VDJ",
        color: "red",
        icon: "hyundaiSvg",
        fuel_type: "petrol 91",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "economic",
        dail_km_limit: "200.00",
    },
    {
        make_model: "Toyota Camry",
        year: "2023",
        rent_per_day: "120",
        transmition: "auto",
        mileage: "22432",
        rented_times: "4",
        car_plate: "123 MNA",
        color: "black",
        icon: "toyotaSvg",
        fuel_type: "petrol 95",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "pickup",
        dail_km_limit: "200.00",
    },
    {
        make_model: "XLT (200A) 4X2",
        year: "2023",
        rent_per_day: "120",
        transmition: "auto",
        mileage: "22432",
        rented_times: "12",
        car_plate: "1253 VDJ",
        color: "blue",
        icon: "fordSvg",
        fuel_type: "petrol 91",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "suv",
        dail_km_limit: "200.00",
    },
    {
        make_model: "Toyota Hilux Double Cab",
        year: "2023",
        rent_per_day: "150",
        transmition: "auto",
        mileage: "22432",
        rented_times: "1",
        car_plate: "1245 TUR",
        color: "black",
        icon: "toyotaSvg",
        fuel_type: "petrol 95",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "economic",
        dail_km_limit: "200.00",
    },
    {
        make_model: "Kia Picanto",
        year: "2016",
        rent_per_day: "120",
        transmition: "auto",
        mileage: "22432",
        rented_times: "12",
        car_plate: "4467 KYT",
        color: "blue",
        icon: "kiaSvg",
        fuel_type: "petrol 91",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "pickup",
        dail_km_limit: "200.00",
    },
    {
        make_model: "Hyundai Tucson",
        year: "2022",
        rent_per_day: "140",
        transmition: "auto",
        mileage: "224432",
        rented_times: "3",
        car_plate: "1773 HGF",
        color: "Purple",
        icon: "hyundaiSvg",
        fuel_type: "petrol 95",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "suv",
        dail_km_limit: "200.00",
    },
    {
        make_model: "Honda Accord",
        year: "2015",
        rent_per_day: "100",
        transmition: "auto",
        mileage: "224377",
        rented_times: "15",
        car_plate: "8976 ANP",
        color: "lightgray",
        icon: "hondaSvg",
        fuel_type: "petrol 91",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "economic",
        dail_km_limit: "200.00",
    },

    {
        make_model: "Sportage Plug-in Hybrid",
        year: "2019",
        rent_per_day: "120",
        transmition: "auto",
        mileage: "22432",
        rented_times: "12",
        car_plate: "1253 VDJ",
        color: "purple",
        icon: "kiaSvg",
        fuel_type: "petrol 95",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "suv",
    },
    {
        make_model: "Nissan Sunny",
        year: "2018",
        rent_per_day: "100",
        transmition: "auto",
        mileage: "274422",
        rented_times: "12",
        car_plate: "1783 UNS",
        color: "black",
        icon: "nissanSvg",
        fuel_type: "petrol 95",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "pickup",
    },
    {
        make_model: "Hyundai Elentra",
        year: "2016",
        rent_per_day: "120",
        transmition: "auto",
        mileage: "22432",
        rented_times: "12",
        car_plate: "1253 VDJ",
        color: "brown",
        icon: "hyundaiSvg",
        fuel_type: "petrol 91",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "sedan",
        dail_km_limit: "200.00",
    },
    {
        make_model: "Nissan Patrol Pickup",
        year: "2019",
        rent_per_day: "100",
        transmition: "manual",
        mileage: "34432",
        rented_times: "12",
        car_plate: "5534 NIA",
        color: "white",
        icon: "nisaanSvg",
        fuel_type: "petrol 95",
        daily_rent: "100.00",
        weekly_rent: "80:00",
        monthly_rent: "70.00",
        extra_km_price: "0.25",
        per_extra_kM: "23.00",
        insurance_provider: "sanad Insurance",
        plate_type: "Private",
        car_type: "pickup",
        dail_km_limit: "200.00",
    },
];
export const Car_chart_data = [
    { id: 0, value: 10, label: "Sedan" },
    { id: 1, value: 15, label: "Econimic" },
    { id: 2, value: 20, label: "Pickup" },
    { id: 2, value: 20, label: "SUV" },
];
export const Contracts_chart_data = [
    { id: 0, value: 10, label: "All" },
    { id: 1, value: 15, label: "Individual" },
    { id: 2, value: 20, label: "Compnay" },
];
export const switch_data = [
    {
        title: "Edit dates",
        info: "Giving the ability to user to change the date",
        name: "isDateEnable",
    },
    {
        title: "Block Customer",
        info: "Giving the user the ability to block customer",
        name: "isBlockEnable",
    },
    {
        title: "Status",
        info: "Determine if the user account active or inactive",
        name: "active",
    },
    {
        title: "Delete Contract",
        info: "Giving the user the ability to delete the closed contract",
        name: "isDeleteContract",
    },
    {
        title: "Discount Receipt",
        info: "Give the user the authority to discount the Pending Receivables.",
        name: "isDiscountReceipt",
    },
    {
        title: "Delete Receipts",
        info: "Give the user the authority to delete the Pending Payables and Receiables. Liquidation bonds are not included in this property",
        name: "isDeleteAvailable",
    },
    {
        title: "Resend To Nozhum",
        info: "For establishments that have activated the link with the systems program, giving the authority to resend all contracts and operations to systems",
        name: "isReSendNozumAvailable",
    },
    {
        title: "Tajeer Rent contract is mandatory",
        info: "You can force the user to issue and return contracts for the rental platform only from the Ministry of Transport, when you activate this feature for the user, he cannot issue regular lease contracts or return them",
        name: "isTajeerAvailable",
    },
    {
        title: "Quick customer creation",
        info: "When this option is disabled, the user will not be able to add a new customer quickly through the Create Lease Contract page, and it requires adding the customer on the Customers page and then opening a new contract for him",
        name: "isQuickAddCustomer",
    },
];
export const language = [
    { label: "English", value: "en" },
    { label: "العربية", value: "ar" },
]
