export interface IContracts {
    message: string,
    result: Contract[]

}
export interface Contract {
    kMIn?: number
    extraKM?: number,
    kMCost?: number
    accessoriesCost?: number
    pricelistLoyalityDiscount?: number
    totalRentCost?: number,
    otherCost?: number,
    discount?: number,
    grossTotal?: number
    vATPercent?: number
    vATAmount?: number
    refunded?: number
    paid?: number
    netTotal?: number
    contractNo: number,
    customerID: number,
    driverID: number,
    carID: number,
    pricelistID: number,
    issueDate: string,
    timeOut: string,
    kmOut: number,
    disputedKMIn?: number
    dailyPrice: number,
    oilChangeCost?: number
    weeklyPrice: number,
    monthlyPrice: number,
    disputedBillingStatus?: string
    sparePartsCost?: number,
    graceHours: string,
    graceHoursPrice: number,
    kmLimit: number,
    extraKmPrice: number,
    advanceAmount: number,
    damageCost?: number,
    actualReturnDate: string,
    disputedSubmitedDatetime?: string
    actualTotalDays: number,
    issueComments: string,
    issueBranchID: number,
    issueBy: string,
    promotionDiscount: number,
    accessoriesID: string,
    status: string,
    tajeer_FuelType: string
    tajeer_FuelLevel: string
    tajeer_OilType: string
    tajeer_OilchangeDate: string,
    tajeer_OilChangeKM: number,
    tajeer_Odometer: number,
    tajeer_AC: string
    tajeer_Stereo: string
    tajeer_Screen: string
    tajeer_Speedometer: string
    tajeer_CarSeat: string
    tajeer_SpareTire: string
    tajeer_SpareTireTools: string
    tajeer_Tires: string
    tajeer_FirstAid: string
    tajeer_Keys: string
    tajeer_FireExtinguisher: string
    tajeer_SafetyTriangle: string
    tajeer_ContractType: string
    tajeer_RentPolicy: string
    tajeer_GeographicalArea: string
    tajeer_Returnbranch: string
    tajeer_CheckList: string
    tajeer_Signature: string
}